import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Script from "next/script";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-W1E1562YQD" />
      <Script>
        {`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-W1E1562YQD');
        `}
      </Script>


      <Script type="text/javascript"/>
      <Script>
        {`
        var Tawk_API=Tawk_API||{ }, Tawk_LoadStart=new Date();
        (function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/6a6cb5020ff60a1d4cf17866/1jusa6gi5';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
})();
`}
      </Script>

      <body className="min-h-full flex flex-col">

        <Header />
        {children}
        <Footer />

      </body>
    </html>
  );
}